[← Back to Documentation](/docs)

Below is documentation for the Query Connector's implementation of an ONC-compliant audit log.

# Standards Referenced

As noted in paragraph (d)(2)(i)(A) of the [ONC Standards Referenced](https://www.healthit.gov/test-method/auditable-events-and-tamper-resistance), the following are data the audit log needs to include

- _7.1.1 Date and Time of Access Event—The exact date and time of the access event and the exit event._
- _7.1.2 Date and Time of Activity—The time to which the data entered refers, if not contemporaneous with user’s data entry_
- _7.1.6 Patient Identification—Unique identification of the patient to distinguish the patient and his/her health information from all others._
- _7.1.7 User Identification—Unique identification of the user of the health information system._
- _7.1.8 Type of Action (for example: creations, additions, deletions, changes, queries, accesses, copy, print, and copy and paste)—Specifies inquiry, any changes made (with pointer to original data state), and a delete specification (with a pointer to deleted information)._
- _7.1.9 Identification of the Patient Data that is Accessed— Granularity should be specific enough to clearly determine if data designated by federal or state law as requiring special confidentiality protection has been accessed. Specific category of data content, such as demographics, pharmacy data, test results, and transcribed notes type, should be identified._

There are subprovisions in paragraphs (d)(2)(i)(B) and (d)(2)(i)(C) for cases when the audit log is disabled and when exported. Since these functions are optional, we’ll leave them out of the initial implementation unless there’s sufficient user demand in subsequent research.

Translating these standards into actions within the Query Connector (referencing the regulation components in parenthesis), the audit log will need to track

1. User creation, role demotion/promotion, group assignment / unassignment, and user sign in and sign out(7.1.7)
   1. User, user group CRUD, and log in and out operations were made auditable in [this PR](https://github.com/CDCgov/dibbs-query-connector/pull/577/files) and validated by [these session management](https://github.com/CDCgov/dibbs-query-connector/pull/584/files#diff-9a93267ba90c49bec61accb50b3fbd098952bba2880e6e655a8db0e9b13d530c) and [these user management](https://github.com/CDCgov/dibbs-query-connector/pull/584/files#diff-ed2978fc4108ba0629806b41219ce952d49b76ff64fbd06106eed9f7ca785f3a) integration tests
2. Query creation and deletion (7.11),
   1. Query building creation, updates and deletion were made auditable in [this PR](https://github.com/CDCgov/dibbs-query-connector/pull/590) and validated by [these integration tests](https://github.com/CDCgov/dibbs-query-connector/pull/590/files#diff-7f668f6f84aa405fb6c3732a7bcc108d006299079b7c3d0955823f6efea4b852)
3. Patient discovery response and viewing patient results (7.1.6, 7.1.9), the user that executed them (7.1.7) and the associated patient query params (7.1.6, 7.1.9)
   1. Patient discovery and patient records were made auditable in [this PR](https://github.com/CDCgov/dibbs-query-connector/pull/550/files#diff-ef77d2110f104bd93df7987d23611ba30c382d26855b2943849c302fdde3c181) and validated by [these integration tests](https://github.com/CDCgov/dibbs-query-connector/pull/584/files#diff-cd2e8ef8f01294dac95fe7ce52e2357e7b5a0ddf7f7337dbd32134560e8e6940)
   2. These integration tests validate the identity of the user executing the query and associated patient parameters are present in the final write to the audit log table
4. The adding of a FHIR server (7.1.8)
   1. FHIR server CRUD operations were made auditable by [this PR](https://github.com/CDCgov/dibbs-query-connector/pull/490/files#diff-61179b27cff2213394d17a79b6337ce02382711957b4db9ef7516e177a0eee17) and validated by [these integration tests](https://github.com/CDCgov/dibbs-query-connector/pull/584/files#diff-1a64b5a29ac8a1d2a83dc1195b37f91dc56825020a89c1d37713d9bffb154307)

All of the above need to be labeled with a timestamp accurate within 5 seconds of the event occurring to comply with 7.1.1 / 7.1.2. The log would need to keep information for [ten years past the lifetime of the medical record](https://www.astm.org/e2147-18.html#:~:text=at%20least%2010%20years%20or%20for%20two%20years%20after%20the%20legal%20age%20of%20majority%2C%20unless%20a%20longer%20period%20of%20record%20retention%20is%20prescribed%20by%20state%2C%20federal%20or%20other%20law%20or%20regulation.), which in our case, is the point at which query results are returned. This means any audit entries can be deleted after ten years.

- The audit event creation timestamp is synchronously [generated by Javascript](https://github.com/CDCgov/dibbs-query-connector/blob/main/src/app/backend/auditLogs/lib.ts#L38) prior to the write to the database within 5 seconds of the event occurring

These messages will need to be exposed according to the regulations set forth in the [audit reports regulation](https://www.healthit.gov/test-method/audit-reports), which mandate the audit log be sorted chronologically and with the ability to filter by start and end date.

- The audit log viewing page [fetches and displays audit entries in reverse chronological order](https://github.com/CDCgov/dibbs-query-connector/blob/5991233914fd37d0b88a767f52b177db15cbd3e8/src/app/backend/dbServices/audit-logs.ts#L14) and the user then has [the ability to filter by start and end date](<https://github.com/CDCgov/dibbs-query-connector/blob/main/src/app/(pages)/auditLogs/page.tsx#L116>)

The audit log must be able to determine when information has been tampered with in accordance with subpoint v) of regulation 170.315 (d)(2). ONC recommends [using a hashing standard with strength equal or greater than SHA-2](https://www.federalregister.gov/documents/2012/09/04/2012-20982/health-information-technology-standards-implementation-specifications-and-certification-criteria-for#p-890) to determine when unauthorized changes to the database may have occurred.

- The audit table is prevented from being updated or deleted via a Postgres macro introduced in [this PR](https://github.com/CDCgov/dibbs-query-connector/pull/497) and validated by [this integration test](https://github.com/CDCgov/dibbs-query-connector/blob/main/src/app/tests/integration/audit-log/general.test.ts#L84)
- The audit log [generates a SHA-256 checksum](https://github.com/CDCgov/dibbs-query-connector/blob/main/src/app/backend/auditLogs/lib.ts#L73) based on author, timestamp, and message contents to determine if there are any changes to the written audit log data
