version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "jose"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@next/bundle-analyzer"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
