changelog:
  categories:
    - title: 🏕 Features
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
          - tech debt
          - chore
    - title: 👒 Dependencies
      labels:
        - dependencies
