# action.yml
name: 'Azure Terraform'
description: 'Login to Azure and Terraform'
inputs:
  sp-creds:
    description: "Azure Service Principal creds"
    required: true

runs:
  using: "composite"
  steps:
    - uses: azure/login@1f63701bf3e6892515f1b7ce2d2bf1708b46beaf
      with:
        creds: ${{ inputs.sp-creds }}

    - name: Terraform Auth
      env:
        AZURE_CREDENTIALS: ${{ inputs.sp-creds }}
      run: |
        # Parse Azure secret into Terraform variables
        $servicePrincipal = ($env:AZURE_CREDENTIALS | ConvertFrom-Json)
        $env:ARM_CLIENT_ID = $servicePrincipal.clientId
        $env:ARM_CLIENT_SECRET = $servicePrincipal.clientSecret
        $env:ARM_SUBSCRIPTION_ID = $servicePrincipal.subscriptionId
        $env:ARM_TENANT_ID = $servicePrincipal.tenantId
          
        # Save environment variable setup for subsequent steps
        Get-ChildItem -Path Env: -Recurse -Include ARM_* | ForEach-Object {Write-Output "$($_.Name)=$($_.Value)"} >> $env:GITHUB_ENV
      shell: pwsh
