repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: pretty-format-json
        name: Pretty Format JSON
        args: [--autofix, --no-sort-keys]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.29.0"
    hooks:
      - id: eslint
        name: ESLint
        files: ^.*\.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint@8.56.0
          - eslint-config-next
          - eslint-config-prettier
          - "@typescript-eslint/parser"
          - "@typescript-eslint/eslint-plugin"
          - typescript
          - "@next/eslint-plugin-next"
          - eslint-plugin-unused-imports
          - eslint-plugin-jsdoc
        args: ["--config=./.eslintrc.json", "--fix"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: Prettier
        types_or: [css, javascript, tsx, ts, yaml]
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: [pretty-format-json]
  submodules: false
