services:
  # PostgreSQL DB for custom query and value set storage
  db:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=tefca_db

    volumes:
      - ./vs_dump.sql:/docker-entrypoint-initdb.d/vs_dump.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 20

  # Flyway migrations and DB version control
  flyway:
    image: flyway/flyway:10.16-alpine
    command: -configFiles=/flyway/conf/flyway.conf -schemas=public -connectRetries=60 migrate
    platform: linux/amd64
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/conf/flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      db:
        condition: service_started

  # Aidbox
  aidbox_db:
    image: healthsamurai/aidboxdb:17
    volumes:
      - aidbox_pg_data:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_USER: aidbox
      POSTGRES_PORT: "5432"
      POSTGRES_DB: aidbox
      POSTGRES_PASSWORD: gOxAmiyiz4

  aidbox:
    image: healthsamurai/aidboxone:stable
    pull_policy: always
    depends_on:
      - aidbox_db
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      AIDBOX_TERMINOLOGY_SERVICE_BASE_URL: https://tx.fhir.org/r4
      AIDBOX_FHIR_PACKAGES: hl7.fhir.r4.core#4.0.1
      AIDBOX_FHIR_SCHEMA_VALIDATION: true
      AIDBOX_CREATED_AT_URL: https://aidbox.app/ex/createdAt
      AIDBOX_CLIENT_SECRET: L6AGe_5V2O
      AIDBOX_CORRECT_AIDBOX_FORMAT: true
      AIDBOX_ADMIN_PASSWORD: OC1MzJ5QNV
      AIDBOX_COMPLIANCE: enabled
      AIDBOX_SECURITY_AUDIT__LOG_ENABLED: true
      BOX_SEARCH_FHIR__COMPARISONS: true
      PGHOST: aidbox_db
      BOX_COMPATIBILITY_VALIDATION_JSON__SCHEMA_REGEX: "#{:fhir-datetime}"
      BOX_SEARCH_AUTHORIZE_INLINE_REQUESTS: true
      PGUSER: aidbox
      AIDBOX_PORT: 8080
      PGDATABASE: aidbox
      PGPASSWORD: gOxAmiyiz4
      PGPORT: "5432"
      BOX_SEARCH_INCLUDE_CONFORMANT: true
  aidbox-seeder:
    build:
      context: .
      dockerfile: Dockerfile.aidbox-seeder
    volumes:
      - ./src/app/tests/assets/GoldenSickPatient.json:/data/GoldenSickPatient.json
      - ./logs:/var/log
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      aidbox:
        condition: service_started
      flyway:
        condition: service_completed_successfully
  
  query-connector:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    env_file:
      - .env.e2e
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:pw@db:5432/tefca_db
    depends_on:
      db:
        condition: service_healthy
      aidbox-seeder:
        condition: service_completed_successfully

volumes:
  aidbox_pg_data:
