-- 1. Add the new 'category' column to the conditions table
ALTER TABLE conditions
ADD COLUMN category TEXT;

-- 2. Create a staging table to hold the CSV data
CREATE TABLE IF NOT EXISTS category_data (
    condition_name TEXT,
    condition_code TEXT,
    category TEXT
);

-- 3. Load the CSV data into the staging table via INSERT
INSERT INTO category_data VALUES('Acanthamoeba', '49649001', 'Waterborne (not enteric)');
INSERT INTO category_data VALUES('Acute Flaccid Myelitis (AFM)', '897031002', 'Neurological Diseases');
INSERT INTO category_data VALUES('Agricultural Chemicals (Fertilizer) Poisoning', '216809001', 'Toxic Effects of Non-Medicinal Substances');
INSERT INTO category_data VALUES('Alpha-gal Syndrome', '788781001', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Amebiasis', '388759003', 'Enteric Diseases');
INSERT INTO category_data VALUES('Anaplasmosis', '13906002', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Anencephaly', '89369001', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Angiostrongyliasis ', '61750000', 'Zoonotic Diseases');
INSERT INTO category_data VALUES('Animal Bite Injury', '399907009', 'Injuries, NEC');
INSERT INTO category_data VALUES('Anthrax', '409498004', 'Zoonotic Diseases');
INSERT INTO category_data VALUES('Arboviral Disease [Other]', '40610006', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Arsenic Exposure and Toxicity', '767146004', 'Toxic Effects of Non-Medicinal Substances');
INSERT INTO category_data VALUES('Asbestosis', '22607003', 'Respiratory Conditions (non-infectious)');
INSERT INTO category_data VALUES('Atrioventricular septal defect (Endocardial cushion defect)', '1237074000', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Babesiosis', '21061004', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Balamuthia mandrillaris Disease', '115635005', 'Waterborne (not enteric)');
INSERT INTO category_data VALUES('Bartonellosis', '266123003', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Baylisascariasis', '93614002', 'Zoonotic Diseases');
INSERT INTO category_data VALUES('Blastomycosis', '69996000', 'Respiratory Conditions (Infectious)');
INSERT INTO category_data VALUES('Botulism', '398565003', 'Toxic Effects of Non-Medicinal Substances');
INSERT INTO category_data VALUES('Botulism, Infant', '414488002', 'Toxic Effects of Non-Medicinal Substances');
INSERT INTO category_data VALUES('Brucellosis', '75702008', 'Zoonotic Diseases');
INSERT INTO category_data VALUES('Byssinosis', '85761009', 'Respiratory Conditions (non-infectious)');
INSERT INTO category_data VALUES('Cadmium Exposure and Toxicity ', '3398004', 'Toxic Effects of Non-Medicinal Substances');
INSERT INTO category_data VALUES('California Serogroup Virus Disease', '418182000', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Campylobacteriosis', '86500004', 'Enteric Diseases');
INSERT INTO category_data VALUES('Cancer', '363346000', 'Cancer');
INSERT INTO category_data VALUES('Candida auris infection', '865929003', 'Healthcare-Associated Events');
INSERT INTO category_data VALUES('Carbapenem-resistant Acinetobacter baumannii (CRAB)', '715174007', 'Healthcare-Associated Events');
INSERT INTO category_data VALUES('Carbapenem-resistant Enterobacteriaceae (CRE)', '712662001', 'Healthcare-Associated Events');
INSERT INTO category_data VALUES('Carbapenem-resistant Pseudomonas aeruginosa (CRPA)', '726492000', 'Healthcare-Associated Events');
INSERT INTO category_data VALUES('Carbapenemase-Producing Organisms (CPO)', '734350003', 'Healthcare-Associated Events');
INSERT INTO category_data VALUES('Carbon Monoxide Poisoning', '17383000', 'Toxic Effects of Non-Medicinal Substances');
INSERT INTO category_data VALUES('Catheter-associated Urinary Tract Infection (CAUTI)', '700372006', 'Healthcare-Associated Events');
INSERT INTO category_data VALUES('Central Line-associated Bloodstream Infection (CLABSI)', '736152001', 'Healthcare-Associated Events');
INSERT INTO category_data VALUES('Chagas Disease', '77506005', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Chancroid', '266143009', 'Sexually Transmitted Diseases');
INSERT INTO category_data VALUES('Chemical Pneumonitis', '233733000', 'Respiratory Conditions (non-infectious)');
INSERT INTO category_data VALUES('Chikungunya virus disease ', '111864006', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Chlamydia trachomatis Infection', '240589008', 'Sexually Transmitted Diseases');
INSERT INTO category_data VALUES('Cholera', '63650001', 'Enteric Diseases');
INSERT INTO category_data VALUES('Cleft Lip Alone', '80281008', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Cleft Lip with Cleft Palate', '66948001', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Cleft Palate Alone', '87979003', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Clostridioides difficile (C. diff) infection', '186431008', 'Enteric Diseases');
INSERT INTO category_data VALUES('Clostridium perfringens Infection', '65154009', 'Enteric Diseases');
INSERT INTO category_data VALUES('Coal Workers'' Pneumoconiosis (CWP)', '29422001', 'Respiratory Conditions (non-infectious)');
INSERT INTO category_data VALUES('Coarctation of the Aorta', '7305005', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Coccidioidomycosis', '60826002', 'Respiratory Conditions (Infectious)');
INSERT INTO category_data VALUES('Colorado tick fever', '6452009', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Congenital cytomegalovirus (cCMV) infection and disease', '59527008', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Congenital Rubella Syndrome (CRS)', '1857005', 'Vaccine Preventable Diseases');
INSERT INTO category_data VALUES('COVID-19', '840539006', 'Respiratory Conditions (Infectious)');
INSERT INTO category_data VALUES('Creutzfeldt-Jakob Disease (CJD) and Variant Creutzfeldt-Jakob Disease (vCJD)', '792004', 'Neurological Diseases');
INSERT INTO category_data VALUES('Cryptococcosis', '42386007', 'Respiratory Conditions (Infectious)');
INSERT INTO category_data VALUES('Cryptosporidiosis', '240370009', 'Enteric Diseases');
INSERT INTO category_data VALUES('Cyanobacteria and Cyanotoxin Poisoning', '41439009', 'Toxic Effects of Non-Medicinal Substances');
INSERT INTO category_data VALUES('Cyclosporiasis', '240372001', 'Enteric Diseases');
INSERT INTO category_data VALUES('Cysticercosis ', '59051007', 'Zoonotic Diseases');
INSERT INTO category_data VALUES('Dengue Virus Infection', '38362002', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Diphtheria', '276197005', 'Vaccine Preventable Diseases');
INSERT INTO category_data VALUES('Diphyllobothriasis', '187151009', 'Zoonotic Diseases');
INSERT INTO category_data VALUES('Double Outlet Right Ventricle (DORV)', '7484005', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Down Syndrome', '41040004', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Drowning and Submersion', '212962007', 'Injuries, NEC');
INSERT INTO category_data VALUES('Drug Overdose and Poisoning, Non-opioid', '1149222004', 'Injuries, NEC');
INSERT INTO category_data VALUES('Eastern equine encephalitis virus disease ', '416925005', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Ebstein Anomaly', '204357006', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Echinococcosis', '74942003', 'Parasitic Diseases, NEC');
INSERT INTO category_data VALUES('Ehrlichiosis', '240626005', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Encephalitis', '45170000', 'Neurological Diseases');
INSERT INTO category_data VALUES('Farmer''s Lung', '18690003', 'Respiratory Conditions (non-infectious)');
INSERT INTO category_data VALUES('Gastroschisis', '72951007', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Genital Warts', '266113007', 'Sexually Transmitted Diseases');
INSERT INTO category_data VALUES('Giardiasis', '58265007', 'Enteric Diseases');
INSERT INTO category_data VALUES('Glanders', '4639008', 'Zoonotic Diseases');
INSERT INTO category_data VALUES('Gonorrhea', '15628003', 'Sexually Transmitted Diseases');
INSERT INTO category_data VALUES('Granuloma Inguinale (Donovanosis)', '28867007', 'Sexually Transmitted Diseases');
INSERT INTO category_data VALUES('Guillain-BarrÃ© Syndrome', '40956001', 'Neurological Diseases');
INSERT INTO category_data VALUES('Gunshot Wound', '283545005', 'Injuries, NEC');
INSERT INTO category_data VALUES('Hansen''s disease', '81004002', 'Respiratory Conditions (Infectious)');
INSERT INTO category_data VALUES('Hantavirus Infection', '359761005', 'Zoonotic Diseases');
INSERT INTO category_data VALUES('Head Injury', '82271004', 'Injuries, NEC');
INSERT INTO category_data VALUES('Hemolytic uremic syndrome (HUS)', '111407006', 'Enteric Diseases');
INSERT INTO category_data VALUES('Hepatitis A Virus Infection', '40468003', 'Enteric Diseases');
INSERT INTO category_data VALUES('Hepatitis B Virus Infection', '66071002', 'Bloodborne Diseases');
INSERT INTO category_data VALUES('Hepatitis B Virus Infection, Perinatal', '60498001', 'Bloodborne Diseases');
INSERT INTO category_data VALUES('Hepatitis C Virus Infection', '50711007', 'Bloodborne Diseases');
INSERT INTO category_data VALUES('Hepatitis C Virus Infection, Perinatal', '551611000124101', 'Bloodborne Diseases');
INSERT INTO category_data VALUES('Hepatitis D Virus Infection', '707341005', 'Bloodborne Diseases');
INSERT INTO category_data VALUES('Hepatitis E Virus Infection', '7111000119109', 'Enteric Diseases');
INSERT INTO category_data VALUES('Hepatitis G Virus Infection', '397575003', 'Bloodborne Diseases');
INSERT INTO category_data VALUES('Herpes, Genital', '33839006', 'Sexually Transmitted Diseases');
INSERT INTO category_data VALUES('Herpes, Neonatal', '91576008', 'Sexually Transmitted Diseases');
INSERT INTO category_data VALUES('Histoplasmosis', '12962009', 'Respiratory Conditions (Infectious)');
INSERT INTO category_data VALUES('HIV Infection or AIDS', '86406008', 'Sexually Transmitted Diseases');
INSERT INTO category_data VALUES('Hypoplastic Left Heart Syndrome (HLHS)', '62067003', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Infant Hearing Loss', '95821001', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Influenza', '43692000', 'Vaccine Preventable Diseases');
INSERT INTO category_data VALUES('Influenza-Associated Hospitalizations', '719590007', 'Vaccine Preventable Diseases');
INSERT INTO category_data VALUES('Influenza-Associated Mortality', '661761000124109', 'Vaccine Preventable Diseases');
INSERT INTO category_data VALUES('Influenza-associated pediatric mortality', '6142004', 'Vaccine Preventable Diseases');
INSERT INTO category_data VALUES('Influenza-like Illness (ILI)', '95891005', 'Respiratory Conditions (Infectious)');
INSERT INTO category_data VALUES('Interrupted Aortic Arch', '218728005', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Invasive Cronobacter Infection Among Infants', '444664004', 'Systemic Conditions');
INSERT INTO category_data VALUES('Invasive Haemophilus Influenzae Disease', '406583002', 'Vaccine Preventable Diseases');
INSERT INTO category_data VALUES('Invasive Pneumococcal Disease', '406617004', 'Vaccine Preventable Diseases');
INSERT INTO category_data VALUES('Jamestown Canyon virus disease', '41723001', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Japanese encephalitis virus (JEV) disease', '52947006', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Kawasaki Disease', '75053002', 'Systemic Conditions');
INSERT INTO category_data VALUES('Keystone virus disease', '404237007', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('La Crosse virus disease', '61094002', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Lead in Blood', '407152001', 'Toxic Effects of Non-Medicinal Substances');
INSERT INTO category_data VALUES('Legionellosis', '26726000', 'Respiratory Conditions (Infectious)');
INSERT INTO category_data VALUES('Leishmaniasis', '80612004', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Leptospirosis', '77377001', 'Zoonotic Diseases');
INSERT INTO category_data VALUES('Limb Reduction', '67341007', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Listeriosis', '4241002', 'Enteric Diseases');
INSERT INTO category_data VALUES('Louse-borne relapsing fever (LBRF)', '14683004', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Lyme Disease', '23502006', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Lymphatic Filariasis', '240820001', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Lymphocytic Choriomeningitis', '721781004', 'Zoonotic Diseases');
INSERT INTO category_data VALUES('Malaria', '61462000', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Measles', '14189004', 'Vaccine Preventable Diseases');
INSERT INTO category_data VALUES('Melioidosis', '428111003', 'Waterborne (not enteric)');
INSERT INTO category_data VALUES('Meningitis', '7180009', 'Neurological Diseases');
INSERT INTO category_data VALUES('Meningococcal disease', '23511006', 'Vaccine Preventable Diseases');
INSERT INTO category_data VALUES('Mercury Exposure and Toxicity', '767299002', 'Toxic Effects of Non-Medicinal Substances');
INSERT INTO category_data VALUES('Methemoglobinemia', '38959009', 'Systemic Conditions');
INSERT INTO category_data VALUES('Middle East Respiratory Syndrome (MERS)', '651000146102', 'Respiratory Conditions (Infectious)');
INSERT INTO category_data VALUES('Motor Vehicle Injury', '407153006', 'Injuries, NEC');
INSERT INTO category_data VALUES('Mpox', '359814004', 'Zoonotic Diseases');
INSERT INTO category_data VALUES('Multisystem Inflammatory Syndrome in Adults (MIS-A)', '1119306006', 'Systemic Conditions');
INSERT INTO category_data VALUES('Multisystem Inflammatory Syndrome in Children (MIS-C)', '895448002', 'Systemic Conditions');
INSERT INTO category_data VALUES('Mumps', '36989005', 'Vaccine Preventable Diseases');
INSERT INTO category_data VALUES('Naegleria fowleri Primary Amebic Meningoencephalitis', '428175000', 'Waterborne (not enteric)');
INSERT INTO category_data VALUES('Neonatal Abstinence Syndrome', '414819007', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Nipah Virus Infection', '406597005', 'Zoonotic Diseases');
INSERT INTO category_data VALUES('Non-pestis Yersiniosis', '83436008', 'Enteric Diseases');
INSERT INTO category_data VALUES('Non-Polio Enterovirus Infection', '53648006', 'Enteric Diseases');
INSERT INTO category_data VALUES('Non-Streptococcal Toxic Shock Syndrome', '18504008', 'Toxic Effects of Non-Medicinal Substances');
INSERT INTO category_data VALUES('Nongonococcal Urethritis', '84619001', 'Sexually Transmitted Diseases');
INSERT INTO category_data VALUES('Nontuberculous Mycobacteria Infection, Extrapulmonary ', '111811007', 'Waterborne (not enteric)');
INSERT INTO category_data VALUES('Nontuberculous Mycobacteria Infection, Pulmonary', '1731000119106', 'Respiratory Conditions (Infectious)');
INSERT INTO category_data VALUES('Norovirus infection', '721763002', 'Enteric Diseases');
INSERT INTO category_data VALUES('Novel Influenza A Virus Infection', '541131000124102', 'Vaccine Preventable Diseases');
INSERT INTO category_data VALUES('Ophthalmia Neonatorum', '34298002', 'Sexually Transmitted Diseases');
INSERT INTO category_data VALUES('Opioid Overdose and Poisoning', '242253008', 'Toxic Effects of Non-Medicinal Substances');
INSERT INTO category_data VALUES('Orthopoxvirus Disease', '414015000', 'Vaccine Preventable Diseases');
INSERT INTO category_data VALUES('Parkinson''s disease', '49049000', 'Neurological Diseases');
INSERT INTO category_data VALUES('Pelvic Inflammatory Disease', '198130006', 'Sexually Transmitted Diseases');
INSERT INTO category_data VALUES('Pertussis', '27836007', 'Vaccine Preventable Diseases');
INSERT INTO category_data VALUES('Pesticide Related Illness or injury', '37131007', 'Toxic Effects of Non-Medicinal Substances');
INSERT INTO category_data VALUES('Phenylketonuria ', '190687004', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Plague', '58750007', 'Zoonotic Diseases');
INSERT INTO category_data VALUES('Poliovirus Infection', '398102009', 'Vaccine Preventable Diseases');
INSERT INTO category_data VALUES('Powassan virus disease ', '416707008', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Primary Congenital Hypothyroidism', '190268003', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Prion Disease (Human) ', '20484008', 'Neurological Diseases');
INSERT INTO category_data VALUES('Psittacosis', '75116005', 'Respiratory Conditions (Infectious)');
INSERT INTO category_data VALUES('Pulmonary Valve Atresia and Stenosis', '204339005', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Q Fever', '186788009', 'Zoonotic Diseases');
INSERT INTO category_data VALUES('Rabies (Human)', '14168008', 'Zoonotic Diseases');
INSERT INTO category_data VALUES('Respiratory Syncytial Virus (RSV)', '6415009', 'Respiratory Conditions (Infectious)');
INSERT INTO category_data VALUES('Respiratory Syncytial Virus (RSV)-Associated Mortality', '55735004', 'Respiratory Conditions (Infectious)');
INSERT INTO category_data VALUES('Reye''s Syndrome', '74351001', 'Systemic Conditions');
INSERT INTO category_data VALUES('Rheumatic Fever', '58718002', 'Streptococcal Diseases');
INSERT INTO category_data VALUES('Ricin Poisoning', '409617000', 'Toxic Effects of Non-Medicinal Substances');
INSERT INTO category_data VALUES('Rotavirus Disease', '18624000', 'Enteric Diseases');
INSERT INTO category_data VALUES('Rubella', '36653000', 'Vaccine Preventable Diseases');
INSERT INTO category_data VALUES('S. Paratyphi Infection', '85904008', 'Enteric Diseases');
INSERT INTO category_data VALUES('S. Typhi Infection', '4834000', 'Enteric Diseases');
INSERT INTO category_data VALUES('Salmonellosis', '302231008', 'Enteric Diseases');
INSERT INTO category_data VALUES('Scabies', '128869009', 'Parasitic Diseases, NEC');
INSERT INTO category_data VALUES('Seafood Poisoning', '269275003', 'Toxic Effects of Non-Medicinal Substances');
INSERT INTO category_data VALUES('Severe Acute Respiratory Syndrome (SARS)', '398447004', 'Respiratory Conditions (Infectious)');
INSERT INTO category_data VALUES('Shiga toxin-producing Escherichia coli (STEC) infection', '328291000119103', 'Enteric Diseases');
INSERT INTO category_data VALUES('Shigellosis', '36188001', 'Enteric Diseases');
INSERT INTO category_data VALUES('Silicosis or pneumoconiosis due to dust containing silica', '805002', 'Respiratory Conditions (non-infectious)');
INSERT INTO category_data VALUES('Single Ventricle', '45503006', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Smallpox', '67924001', 'Vaccine Preventable Diseases');
INSERT INTO category_data VALUES('Snowshoe hare virus disease', '404236003', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Spina Bifida', '67531005', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Spotted Fever Rickettsiosis', '186771002', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('St. Louis Encephalitis Virus Infection', '417192005', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Staphylococcal Enterotoxin B Poisoning', '419488004', 'Toxic Effects of Non-Medicinal Substances');
INSERT INTO category_data VALUES('Staphylococcus aureus Infection', '406602003', 'Healthcare-Associated Events');
INSERT INTO category_data VALUES('Streptococcal disease, invasive, Group A', '406614006', 'Streptococcal Diseases');
INSERT INTO category_data VALUES('Streptococcal disease, invasive, Group B', '406612005', 'Streptococcal Diseases');
INSERT INTO category_data VALUES('Streptococcal Toxic Shock Syndrome', '240451000', 'Toxic Effects of Non-Medicinal Substances');
INSERT INTO category_data VALUES('Strongyloidiasis', '1214006', 'Parasitic Diseases, NEC');
INSERT INTO category_data VALUES('Suicide', '44301001', 'Injuries, NEC');
INSERT INTO category_data VALUES('Surgical Site Infection (SSI)', '433202001', 'Healthcare-Associated Events');
INSERT INTO category_data VALUES('Syphilis', '76272004', 'Sexually Transmitted Diseases');
INSERT INTO category_data VALUES('Syphilis, Congenital', '35742006', 'Sexually Transmitted Diseases');
INSERT INTO category_data VALUES('Taeniasis', '76172008', 'Zoonotic Diseases');
INSERT INTO category_data VALUES('Tetanus', '76902006', 'Vaccine Preventable Diseases');
INSERT INTO category_data VALUES('Tetralogy of Fallot (TOF)', '86299006', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Tick Paralysis', '74225001', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Tickborne relapsing fever (TBRF)', '10301003', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Total Anomalous Pulmonary Venous Connection (TAPVC)', '111323005', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Toxoplasmosis', '187192000', 'Zoonotic Diseases');
INSERT INTO category_data VALUES('Transposition of the Great Arteries (TGA)', '204296002', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Trichinellosis', '709018004', 'Zoonotic Diseases');
INSERT INTO category_data VALUES('Tricuspid Valve Atresia and Stenosis', '4374004', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Trivittatus virus disease', '240507007', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Truncus Arteriosus (Common Truncus)', '61959006', 'Birth Defects and Infant Disorders');
INSERT INTO category_data VALUES('Tuberculosis', '56717001', 'Respiratory Conditions (Infectious)');
INSERT INTO category_data VALUES('Tuberculosis, Latent Infection (LTBI)', '11999007', 'Respiratory Conditions (Infectious)');
INSERT INTO category_data VALUES('Tularemia', '19265001', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Typhus Fever', '240613006', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Vaccine Adverse Event', '293104008', 'Healthcare-Associated Events');
INSERT INTO category_data VALUES('Vaccinia Disease or Adverse Event', '409636005', 'Healthcare-Associated Events');
INSERT INTO category_data VALUES('Vancomycin-intermediate Staphylococcus aureus (VISA)', '406604002', 'Healthcare-Associated Events');
INSERT INTO category_data VALUES('Vancomycin-resistant Enterococci (VRE) Infection', '406575008', 'Healthcare-Associated Events');
INSERT INTO category_data VALUES('Vancomycin-resistant Staphylococcus aureus (VRSA)', '404681006', 'Healthcare-Associated Events');
INSERT INTO category_data VALUES('Varicella', '38907003', 'Vaccine Preventable Diseases');
INSERT INTO category_data VALUES('Ventilator-associated Event (VAE)', '71695001', 'Healthcare-Associated Events');
INSERT INTO category_data VALUES('Vesicular Stomatitis ', '36921006', 'Zoonotic Diseases');
INSERT INTO category_data VALUES('Vibriosis', '398557001', 'Enteric Diseases');
INSERT INTO category_data VALUES('Viral Hemorrhagic Fever (VHF)', '240523007', 'Zoonotic Diseases');
INSERT INTO category_data VALUES('West Nile Virus Infection', '417093003', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Western equine encephalitis virus disease ', '47523006', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Work-related Asthma (WRA)', '57607007', 'Respiratory Conditions (non-infectious)');
INSERT INTO category_data VALUES('Yellow Fever', '16541001', 'Vectorborne Diseases');
INSERT INTO category_data VALUES('Zika Virus Disease', '3928002', 'Vectorborne Diseases');

-- 4. Update the condition table with the category from the staging table
UPDATE conditions
SET category = category_data.category
FROM category_data
WHERE conditions.id = category_data.condition_code;

-- 5. Add hardcoded categories from DIBBs-specific additions
UPDATE conditions
SET category = 'Birth Defects and Infant Disorders'
WHERE conditions.name = 'Newborn Screening';

UPDATE conditions
SET category = 'Cancer'
WHERE conditions.name = 'Cancer (Leukemia)';

-- 6. Drop the staging table after the join
DROP TABLE category_data;
