services:
  # Postgresql DB
  db:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=tefca_db
      # Note: you must have a local .env file with the DATABASE_URL set to the following:
      # DATABASE_URL=postgresql://postgres:pw@localhost:5432/tefca_db
      # Note: you must have a local .env file with the ERSD_API_KEY set to a key
      # obtained from the ERSD API at https://ersd.aimsplatform.org/#/api-keys
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 20

  # Flyway migrations and DB version control
  flyway:
    image: flyway/flyway:10.16-alpine
    command: -configFiles=/flyway/conf/flyway.conf -schemas=public -connectRetries=60 migrate
    platform: linux/amd64
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/conf/flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      db:
        condition: service_started

  # HAPI FHIR Server for running e2e tests
  hapi-fhir-server:
    image: "hapiproject/hapi:latest"
    ports:
      - "8080:8080"
  data-loader:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - "./src/app/tests/assets/GoldenSickPatient.json:/etc/GoldenSickPatient.json"
      - "./post_e2e_data_hapi.sh:/post_e2e_data_hapi.sh"
    command: ["sh", "post_e2e_data_hapi.sh"]
    depends_on:
      - hapi-fhir-server

  # Keycloak for authentication
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.2
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - keycloak:/opt/keycloak/data/
    restart: always
    command:
      - "start-dev"

volumes:
  keycloak:
