FROM quay.io/keycloak/keycloak:26.1
USER root

# Copy all realm files
COPY ./keycloak/*.json /opt/keycloak/

# Copy selection script
COPY ./keycloak/select-realm.sh /opt/keycloak/select-realm.sh
RUN chmod +x /opt/keycloak/select-realm.sh

# Use script as the entrypoint
USER 1000
CMD ["/opt/keycloak/select-realm.sh"]
