FROM quay.io/keycloak/keycloak:26.1
USER root

# Copy all keycloak files to /opt/keycloak
COPY ./keycloak/ /opt/keycloak/

# Copy selection script
RUN chmod +x /opt/keycloak/select-realm.sh

# Use script as the entrypoint
USER 1000
ENTRYPOINT ["/opt/keycloak/select-realm.sh"]
