name: CD

on:
  merge_group:
    types:
      - checks_requested
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Query Connector Image
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    steps:
      - name: Check Out Changes
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: lowercase repo name to use in following step
        env:
          REPO: ${{ github.repository }}
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Set up Python (for yq)
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install yq
        run: pip install yq semver

      - name: Get current qc version
        id: current-version
        run: |
          CURRENT_VERSION=$(yq '.version' query-connector/app_version.yml)
          echo "Current Query Connector Version: $CURRENT_VERSION"
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Increment qc version
        id: increment-version
        run: |
          VERSION_PART=${{ github.event.inputs.bump_patch || 'patch' }}
          echo "Debug: env.current_version=${{ env.current_version }}"  # Debug log
          NEW_VERSION=$(python -c "from semver import VersionInfo as V; print(V.parse('${{ env.current_version }}').bump_${VERSION_PART}())")
          echo "New Query Connector Version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Update app_version.yaml
        id: new-version
        run: |
          yq -i -y ".version = \"${{ env.new_version }}\"" query-connector/app_version.yml
          cat query-connector/app_version.yml

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.REPO }}/query-connector
          tags: |
            type=semver,pattern={{version}},value=${{ steps.new-version.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.new-version.outputs.version }}
            type=semver,pattern={{major}},value=${{ steps.new-version.outputs.version }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./query-connector
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
