name: Deploy Query Connector to demo site

on:
  merge_group:
    types:
      - checks_requested
  push:
    branches:
      - main
      - shanice/automated-workflow-deployment
  workflow_dispatch:
    inputs:
      target_service:
        description: "Input a service name (e.g., demo-app)"
        required: true
      target_version:
        description: "Input a version (e.g., v1.0.0)"
      target_repo_owner:
        description: "Input for repository owner"
        required: true
      target_repo_name:
        description: "Input for the name of the repository"
      target_event_type:
        description: "Input for the event type that is configured as the trigger for the workflow"     
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_image:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    steps:
      - uses: actions/checkout@v4
      - name: Build and Push Image
        uses: ./.github/actions/build-and-push
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}

  up_helm_chart:
    runs-on: ubuntu-latest
    needs: [build_image]
    steps:
      - uses: actions/checkout@v4
      - name: Increment chart version
        uses: ./.github/actions/trigger-remote-workflow
        with:
          target_service: ${{ github.event.inputs.target_service || 'helm-chart' }}
          target_version: ${{ github.event.inputs.target_version || 'v1.0.0' }}
          deployment_auth: ${{ secrets.DEPLOYMENT_WORKFLOW }}
          target_repo_owner: ${{ github.event.inputs.target_repo_owner || 'CDCgov' }}
          target_repo_name: ${{ github.event.inputs.target_repo_name || 'phdi-charts' }}
          target_event_type: ${{ github.event.inputs.target_event_type || 'trigger-workflow' }}

  deploy_image_eks:
    runs-on: ubuntu-latest
    needs: [up_helm_chart]
    steps:
      - uses: actions/checkout@v4
      - name: Increment chart version
        uses: ./.github/actions/trigger-remote-workflow
        with:
          target_service: ${{ github.event.inputs.target_service || 'query-connector' }}
          target_version: ${{ github.event.inputs.target_version || 'v1.0.0' }}
          deployment_auth: ${{ secrets.DEPLOYMENT_WORKFLOW }}
          target_repo_owner: ${{ github.event.inputs.target_repo_owner || 'CDCgov' }}
          target_repo_name: ${{ github.event.inputs.target_repo_name || 'phdi-playground' }}
          target_event_type: ${{ github.event.inputs.target_event_type || 'trigger-workflow' }}
