name: Generate Azure Visualization

on: 
  workflow_dispatch:
    inputs:
      resource-group:
        description: Comma-seperated resource group list
        required: true
        default: prime-ingestion-test
      out-file:
        description: Graph export path
        required: true
        default: output/viz.svg
      depth:
        description: Level of Azure Resource Sub-category to be included in vizualization (1 or 2)
        required: true
        default: 2
      verbosity:
        description: Level of information to included in vizualization (1 or 2)
        required: true
        default: 2
      exclude-types:
        description: Exclude resources via string search
        required: true
        default: '*privateDnsZones*,*microsoft.insights*,*sites/snapshots*,*workspaces/savedSearches*,*Microsoft.Portal*,*sites/deployments*,*routeTables*'

jobs:
  Generate-Azure-Visualization:
    runs-on: ubuntu-latest
    steps:
      - name: Check out changes
        uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.SERVICE_PRINCIPAL_CREDS }}
          enable-AzPSSession: true
      - uses: JosiahSiegel/AzViz-action@v1.0.4
        with:
          resource-group: ${{ github.event.inputs.resource-group }}
          out-file: ${{ github.event.inputs.out-file }}
          sub-name: OCIO-DMZ-C1
          depth: ${{ github.event.inputs.depth }}
          verbosity: ${{ github.event.inputs.verbosity }}
          exclude-types: ${{ github.event.inputs.exclude-types }}
      - uses: actions/upload-artifact@v2
        with:
          name: viz
          path: output/*
