name: Build Keycloak

on:
  push:
    branches:
      - main
      - nickclyde/keycloak-terraform
    paths:
      - "query-connector/Dockerfile.keycloak"
      - "query-connector/keycloak/"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build keycloak
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    steps:
      - name: Check Out Changes
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: lowercase repo name
        env:
          REPO: ${{ github.repository }}
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./query-connector
          file: ./query-connector/Dockerfile.keycloak
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}/keycloak:main, ghcr.io/${{ env.REPO }}/keycloak:latest
