name: Populate Azure "create" tags

on:
  schedule:
    - cron:  '5 5 * * *'
  workflow_dispatch:

env:
  RESOURCE_GROUPS: '["prime-ingestion-dev","prime-ingestion-test"]'

jobs:
  pre_job:
    name: "Set Build Environment"
    runs-on: ubuntu-latest
    outputs:
      rg: ${{ env.RESOURCE_GROUPS }}
    steps:
      - name: Check out changes
        uses: actions/checkout@v2

  populate_create_tags:
    name: "Populate Tags: ${{ matrix.rg }}"
    needs:
      - pre_job
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        rg: ${{ fromJson(needs.pre_job.outputs.rg) }}
    steps:
      - name: Check out changes
        uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.SERVICE_PRINCIPAL_CREDS }}
      - name: Find tag values and add if not already exists
        continue-on-error: true
        uses: ./.github/actions/create-tags
        with:
          resource-group: ${{ matrix.rg }}
          offset-days: 5
