name: Trigger Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      target_service:
        description: "Input a service name (e.g., demo-app)"
        required: true
      target_version:
        description: "Input a version (e.g., v1.0.0)"
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deployment Workflow in PHDI-Playground Repository
        run: |
          # Set the required variables
          repo_owner="REPOSITORY OWNER" 
          repo_name="REPOSITORY NAME"  
          event_type="trigger-workflow" 
          service="${{ github.event.inputs.target_service }}"
          version="${{ github.event.inputs.target_version }}"
           
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DEPLOYMENT_WORKFLOW }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\", \"unit\": false, \"integration\": true}}"
