name: Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

env:
  TEST_RUNNER_JAVA_VERSION: 11
  TEST_RUNNER_NODE_VERSION: 14
  TEST_RUNNER_PYTHON_VERSION: 3.9
  TEST_RUNNER_TERRAFORM_VERSION: 1.1.5

jobs:
  function-app-scan:
    # Find directories that contain function apps in python or java
    #
    # Look for a files in function app directories to determine the language used
    # and output a list of directory names for functions of each language.  Language
    # is determined based on the existence of a file inside the top-level function
    # app directory, currently:
    #     python: `requirements.txt`
    #     java: `pom.xml`
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install jq
      - id: find-python-apps
        name: Scan for python function apps
        # use jq to produce json output and filter out the empty item caused by final newline
        run: |
          echo "::set-output name=pydirs::$(find src/FunctionApps/ -mindepth 2 -maxdepth 2 -type f -name requirements.txt -printf "%P\n" |cut -d/ -f1 |jq --raw-input --slurp 'split("\n")' |jq --compact-output .[0:-1])"
      - id: find-java-apps
        name: Scan for java function apps
        run: |
          echo "::set-output name=javadirs::$(find src/FunctionApps/ -mindepth 2 -maxdepth 2 -type f -name pom.xml -printf "%P\n" |cut -d/ -f1 |jq --raw-input --slurp 'split("\n")' |jq --compact-output .[0:-1])"
      - name: Summary of detected apps
        run: |
          echo "Python (requirements.txt): ${{steps.find-python-apps.outputs.pydirs}}"
          echo "Java (pom.xml): ${{steps.find-java-apps.outputs.javadirs}}"
    outputs:
      python-function-app-dirs: ${{steps.find-python-apps.outputs.pydirs}}
      java-function-app-dirs: ${{steps.find-java-apps.outputs.javadirs}}

  unit-test-python:
    needs: function-app-scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function-to-test: ${{fromJson(needs.function-app-scan.outputs.python-function-app-dirs)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python ${{env.TEST_RUNNER_PYTHON_VERSION}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{env.TEST_RUNNER_PYTHON_VERSION}}
          cache: pip
      - name: Install dependencies
        working-directory: ./src/FunctionApps/${{matrix.function-to-test}}
        run: |
          pip install -U pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run unit tests
        working-directory: ./src/FunctionApps/${{matrix.function-to-test}}
        run: |
          python -m pytest

  unit-test-java:
    needs: function-app-scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function-to-test: ${{fromJson(needs.function-app-scan.outputs.java-function-app-dirs)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java ${{env.TEST_RUNNER_JAVA_VERSION}}
        uses: actions/setup-java@v2
        with:
          java-version: ${{env.TEST_RUNNER_JAVA_VERSION}}
          distribution: adopt
      - name: Setup node ${{env.TEST_RUNNER_NODE_VERSION}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.TEST_RUNNER_NODE_VERSION}}
      - name: Install Azure functions core tools
        run: |
          npm install --global azure-functions-core-tools
      - name: Setup maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
          restore-keys: |
            ${{runner.os}}-maven-
      - name: Verify
        working-directory: ./src/FunctionApps/${{matrix.function-to-test}}
        run: |
          mvn --batch-mode verify

  code-check-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python ${{env.TEST_RUNNER_PYTHON_VERSION}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{env.TEST_RUNNER_PYTHON_VERSION}}
          cache: pip
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install black flake8
      - name: Check format (black)
        run: |
          black --check --verbose .
      - name: Check style (flake8)
        run: |
          flake8

  code-check-terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./operations
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{env.TEST_RUNNER_TERRAFORM_VERSION}}
      - name: Check format
        run: terraform fmt -check -recursive
