name: Terraform Linting
on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tflint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dirs:
          - terraform/bootstrap
          - terraform/azure
          - terraform/aws/redirect
          - terraform/aws/implementation/ecs
          - terraform/aws/implementation/setup
          - terraform/aws/modules/oidc
          - terraform/aws/modules/tfstate

    steps:
      - uses: actions/checkout@v4
        name: Checkout source code

      - uses: actions/cache@v4
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: latest

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init --config "$GITHUB_WORKSPACE/.tflint.hcl"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        working-directory: ${{ github.workspace }}/${{ matrix.dirs }}
        run: tflint -f compact --config "$GITHUB_WORKSPACE/.tflint.hcl"
